// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awwwwtttatecwuqfbgih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3d3d3dHR0YXRlY3d1cWZiZ2loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NjU2MjYsImV4cCI6MjA3MjU0MTYyNn0.w2UmCl5EBzQIASRSl7wkL52i3iPQ75o9Mj0g6eeB_HM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});